baseURL = "https://safeced.com/"
languageCode = "en-us"
title = "Safeced - Security compliance simplified for small businesses."
theme = "slate"
publishDir = "docs"

[menu]
  #[[menu.main]]
  #  name = "Product"
  #  url = "/product/"
  #  weight = 1
  #[[menu.main]]
  #  name = "Pricing"
  #  url = "/pricing/"
  #  weight = 3
  #[[menu.main]]
  #  name = "About"
  #  url = "/about/"
  #  weight = 4
  [[menu.main]]
    name = "Log in"
    url = "https://app.safeced.com"
    weight = 6
  [[menu.main]]
    name = "Create Account"
    url = "https://app.safeced.com/signup/"
    weight = 7