baseURL = "https://devszero.com/"
languageCode = "en-us"
title = "DevsZero - Security simplified for startups."
theme = "slate"
publishDir = "docs"

[menu]
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 1
  [[menu.main]]
    name = "Pricing"
    url = "/pricing/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Demo"
    url = "https://console.devszero.com/demo/"
    weight = 4
  [[menu.main]]
    name = "Get started"
    url = "https://console.devszero.com/signup/"
    weight = 5