baseURL = "https://devszero.com/"
languageCode = "en-us"
title = "DevsZero - Deployment and security simplified for startups."
theme = "slate"
publishDir = "docs"

[menu]
  [[menu.main]]
    name = "Images"
    url = "https://console.devszero.com/images/"
    weight = 1
  [[menu.main]]
    name = "Usecases"
    url = "/usecases/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Get started"
    url = "https://console.devszero.com/signup/"
    weight = 5