baseURL = "https://argoscan.com/"
languageCode = "en-us"
title = "ArgoScan - Security compliance simplified for small businesses."
theme = "slate"
publishDir = "docs"

[menu]
  #[[menu.main]]
  #  name = "Products"
  #  url = "/products/"
  #  weight = 1
  #[[menu.main]]
  #  name = "Pricing"
  #  url = "/pricing/"
  #  weight = 2
  #[[menu.main]]
  #  name = "About"
  #  url = "/about/"
  #  weight = 3
  #[[menu.main]]
  #  name = "Demo"
  #  url = "https://felixcheruiyot.typeform.com/to/G6GHSgFb"
  #  weight = 4
  [[menu.main]]
    name = "Get beta access"
    url = "https://felixcheruiyot.typeform.com/to/G6GHSgFb"
    weight = 5